/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheatsheetsRouteImport } from './routes/cheatsheets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as SheetsSheetIdRouteImport } from './routes/sheets.$sheetId'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMistakesRouteImport } from './routes/_authenticated/mistakes'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedAdminBugReportsRouteImport } from './routes/_authenticated/admin.bug-reports'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetsRoute = CheatsheetsRouteImport.update({
  id: '/cheatsheets',
  path: '/cheatsheets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetsSheetIdRoute = SheetsSheetIdRouteImport.update({
  id: '/sheets/$sheetId',
  path: '/sheets/$sheetId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMistakesRoute = AuthenticatedMistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBugReportsRoute =
  AuthenticatedAdminBugReportsRouteImport.update({
    id: '/bug-reports',
    path: '/bug-reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cheatsheets': typeof CheatsheetsRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/contests': typeof ContestsRoute
  '/design-system': typeof DesignSystemRoute
  '/mentor': typeof MentorRoute
  '/problems': typeof ProblemsRoute
  '/search': typeof SearchRoute
  '/simulator': typeof SimulatorRoute
  '/videos': typeof VideosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/inbox': typeof AuthenticatedInboxRoute
  '/mistakes': typeof AuthenticatedMistakesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sheets/$sheetId': typeof SheetsSheetIdRoute
  '/u/$handle': typeof UHandleRoute
  '/admin/bug-reports': typeof AuthenticatedAdminBugReportsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cheatsheets': typeof CheatsheetsRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/contests': typeof ContestsRoute
  '/design-system': typeof DesignSystemRoute
  '/mentor': typeof MentorRoute
  '/problems': typeof ProblemsRoute
  '/search': typeof SearchRoute
  '/simulator': typeof SimulatorRoute
  '/videos': typeof VideosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/inbox': typeof AuthenticatedInboxRoute
  '/mistakes': typeof AuthenticatedMistakesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sheets/$sheetId': typeof SheetsSheetIdRoute
  '/u/$handle': typeof UHandleRoute
  '/admin/bug-reports': typeof AuthenticatedAdminBugReportsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cheatsheets': typeof CheatsheetsRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/contests': typeof ContestsRoute
  '/design-system': typeof DesignSystemRoute
  '/mentor': typeof MentorRoute
  '/problems': typeof ProblemsRoute
  '/search': typeof SearchRoute
  '/simulator': typeof SimulatorRoute
  '/videos': typeof VideosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/mistakes': typeof AuthenticatedMistakesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/sheets/$sheetId': typeof SheetsSheetIdRoute
  '/u/$handle': typeof UHandleRoute
  '/_authenticated/admin/bug-reports': typeof AuthenticatedAdminBugReportsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cheatsheets'
    | '/community'
    | '/compare'
    | '/contests'
    | '/design-system'
    | '/mentor'
    | '/problems'
    | '/search'
    | '/simulator'
    | '/videos'
    | '/admin'
    | '/inbox'
    | '/mistakes'
    | '/notifications'
    | '/profile'
    | '/sheets/$sheetId'
    | '/u/$handle'
    | '/admin/bug-reports'
    | '/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cheatsheets'
    | '/community'
    | '/compare'
    | '/contests'
    | '/design-system'
    | '/mentor'
    | '/problems'
    | '/search'
    | '/simulator'
    | '/videos'
    | '/admin'
    | '/inbox'
    | '/mistakes'
    | '/notifications'
    | '/profile'
    | '/sheets/$sheetId'
    | '/u/$handle'
    | '/admin/bug-reports'
    | '/settings/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cheatsheets'
    | '/community'
    | '/compare'
    | '/contests'
    | '/design-system'
    | '/mentor'
    | '/problems'
    | '/search'
    | '/simulator'
    | '/videos'
    | '/_authenticated/admin'
    | '/_authenticated/inbox'
    | '/_authenticated/mistakes'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/sheets/$sheetId'
    | '/u/$handle'
    | '/_authenticated/admin/bug-reports'
    | '/_authenticated/settings/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheatsheetsRoute: typeof CheatsheetsRoute
  CommunityRoute: typeof CommunityRoute
  CompareRoute: typeof CompareRoute
  ContestsRoute: typeof ContestsRoute
  DesignSystemRoute: typeof DesignSystemRoute
  MentorRoute: typeof MentorRoute
  ProblemsRoute: typeof ProblemsRoute
  SearchRoute: typeof SearchRoute
  SimulatorRoute: typeof SimulatorRoute
  VideosRoute: typeof VideosRoute
  SheetsSheetIdRoute: typeof SheetsSheetIdRoute
  UHandleRoute: typeof UHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheets': {
      id: '/cheatsheets'
      path: '/cheatsheets'
      fullPath: '/cheatsheets'
      preLoaderRoute: typeof CheatsheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheets/$sheetId': {
      id: '/sheets/$sheetId'
      path: '/sheets/$sheetId'
      fullPath: '/sheets/$sheetId'
      preLoaderRoute: typeof SheetsSheetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mistakes': {
      id: '/_authenticated/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof AuthenticatedMistakesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/bug-reports': {
      id: '/_authenticated/admin/bug-reports'
      path: '/bug-reports'
      fullPath: '/admin/bug-reports'
      preLoaderRoute: typeof AuthenticatedAdminBugReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBugReportsRoute: typeof AuthenticatedAdminBugReportsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBugReportsRoute: AuthenticatedAdminBugReportsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedMistakesRoute: typeof AuthenticatedMistakesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedMistakesRoute: AuthenticatedMistakesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheatsheetsRoute: CheatsheetsRoute,
  CommunityRoute: CommunityRoute,
  CompareRoute: CompareRoute,
  ContestsRoute: ContestsRoute,
  DesignSystemRoute: DesignSystemRoute,
  MentorRoute: MentorRoute,
  ProblemsRoute: ProblemsRoute,
  SearchRoute: SearchRoute,
  SimulatorRoute: SimulatorRoute,
  VideosRoute: VideosRoute,
  SheetsSheetIdRoute: SheetsSheetIdRoute,
  UHandleRoute: UHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
